### ISSUE TITLE
Specify Word Version

### ISSUE THREAD

**Issue by m4ss1m0g** [xceedsoftware/DocX#129]
I made a patch for specify the Word Version.
In short, you have to change the body of `CreateOrGetSettingsPart` method on HelperFunctions.cs from

`<w:compat />`

to

`<w:compat><w:compatSetting w:name='compatibilityMode' w:uri='http://schemas.microsoft.com/office/word' w:val='15'/></w:compat>"`

where  w:val='15' specify the office version.

**Comment by GrabzIt** [comment]
You need to submit a pull request
