### ISSUE TITLE
Table Column Widths

### ISSUE THREAD

**Issue by mobius127** [xceedsoftware/DocX#153]
I have a big problem with this, because I'm trying to fix column widths.

masterTable.SetColumnWidth(0, 300);

what kind of value is 300? 

Centimeters, Inches, Pixels... I can't found any reference of this

**Comment by XceedBoucherS** [comment]
Hi,
It is a value in "dxa", in twentieths of a point (1/1440 of an inch). http://officeopenxml.com/WPtableGrid.php

A twentieth of a point is : http://whatis.techtarget.com/definition/twip-twentieth-of-a-point

Basically, if you divide this 300 by 20, Word will give you a column width of 15 pt.
