### ISSUE TITLE
Is there a way to print with DocX to a physical printer?

### ISSUE THREAD

**Issue by labilbe** [xceedsoftware/DocX#157]
I would like to know if it is possible and if not, what is the most elegant way to do that?
Thanks.

**Comment by XceedBoucherS** [comment]
Hi,

Currently, there is no way to print to a physical printer with DocX.
We are aware of this and we are planning on evaluating this feature.
I don't know if it can help, but the Plus version of DocX : "Xceed Words for .NET" includes a ConvertToPDF method to convert a docx file to a pdf file.

**Comment by labilbe** [comment]
Thank you for your quick answer.
