### ISSUE TITLE
Distribute release v1.1.0 as a NuGet package

### ISSUE THREAD

**Issue by stevenvolckaert** [xceedsoftware/DocX#163]
It would be great if the [DocX](https://www.nuget.org/packages/DocX/) NuGet package is updated with the latest release, v1.1.0.

If you need guidance on how to do this, I can help. Just let me know!

**Comment by XceedBoucherS** [comment]
hi,

Thanks for pointing this out. 
We will look at this to add it to Nuget.

**Comment by stevenvolckaert** [comment]
Great! Thanks a lot!

**Comment by XceedBoucherS** [comment]
Hi,
DocX v1.1 is now available on Nuget.
Thanks.
