### ISSUE TITLE
Outdated Docmentation and DLL

### ISSUE THREAD

**Issue by Iyashu5040** [xceedsoftware/DocX#164]
The getting started video instructs us to download a dll from CodePlex, which is not up to date. Also, the only documentation seems to be a .chm file, also on the outdated CodePlex site. The latest CodePlex files are all well over a year old. The NuGet package listed on the github readme is also over a year old.

Where can we find the latest dll and documentation? Do we have to pull the repo and build the dll manually?

EDIT: I've found the dll download under releases. Maybe just link to that in the readme?

**Comment by XceedBoucherS** [comment]
Hi,

As you found out, the dlls are available on GitHub under tab Code/Releases and documentation is available on GitHub under tab Wiki (which contains a link to the full documentation).

Where can you find the "Getting started" video ?
The Codeplex site is no more updated.
The Nuget package will be updated with the latest release (as well as the link to it on the GitHub  ReadMe.)

**Comment by Iyashu5040** [comment]
Thanks for the clarification on where to find the documentation.

I found the Getting Started video here https://github.com/xceedsoftware/DocX#how-can-i-learn-more

**Comment by XceedBoucherS** [comment]
Hi,

The Nuget package is now updated to v1.1.0, as well as the link to it on the GitHub ReadMe.
We will review the Getting Started video.
Thanks.

**Comment by Iyashu5040** [comment]
Great, thank you.
