### ISSUE TITLE
ReplacePicture is missing

### ISSUE THREAD

**Issue by Iyashu5040** [xceedsoftware/DocX#165]
The documentation at https://xceed.com/wp-content/documentation/xceed-words-for-net/webframe.html#Xceed.Words.NET~Xceed.Words.NET.Paragraph~ReplacePicture.html specifies that there is a `ReplacePicture` method on the `Paragraph` class. I can't find this method in the source code on github and it doesn't exist in the nuget package (v 1.0.0.22). Is this a mistake in the documentation or an omission in the library? Or is this only available in the paid version? I'd really like to have this feature available to use.

**Comment by XceedBoucherS** [comment]
Hi,
The documentation is for "Xceed Word for .NET v1.3", which is the paid version of DocX.
You are currently working(I believe)  with DocX v1.1, which is the free version.

The Nuget package have been updated to DocX v1.1.

But this method is only available starting at v1.2.
You can buy the "Xceed Words for .NET v1.3" here : https://xceed.com/xceed-words-for-net/
or wait for the free "DocX v1.2" to be released. No known dates for now.
