### ISSUE TITLE
BookMarks not being replaced

### ISSUE THREAD

**Issue by JacquesVDZ** [xceedsoftware/DocX#168]
My bookmarks are not being set , I tried 2 ways:

wordDocTemp.Bookmarks["LetterDate"].SetText( "10 February 2012") );
wordDocTemp.InsertAtBookmark( "10 February 2012", "LetterDate" );

It inserts blanks. I cant find any solution on ther internet.

**Comment by CaptainStealthy** [comment]
@JacquesVDZ I have the same problem. Did you ever find a solution?

**Comment by XceedBoucherS** [comment]
Hi,

It should work.
Here's what I tried. 
I create a blank new project, install the latest DocX from NuGet : DocX v1.8.
Create a test.docx containing texts and a bookmark named "LetterDate".
I then used the following code:
` static void Main( string[] args )
    {
      var wordDocTemp = DocX.Load("test.docx");

      wordDocTemp.Bookmarks[ "LetterDate" ].SetText( "10 February 2012" );

      wordDocTemp.SaveAs("output.docx");
    }`
In the resulting "output.docx", I can see the date "10 February 2012" at the bookmark position.

Thank you

**Comment by CaptainStealthy** [comment]
@XceedBoucherS Yes, trying this again with a dummy app was on my todo list for today.

The functionality does in fact, work properly - it doesn't appear to work with bookmarks that are created as 'text form fields'. But when I just type normal text and mark it as a bookmark, that text gets replaced.

Do I need to use the licensed version for updating fields, or is that not supported?

![image](https://user-images.githubusercontent.com/48744965/124499861-f705cb00-dd7b-11eb-8cb6-e5079638b489.png)

**Comment by XceedBoucherS** [comment]
The license version should react the same in regard to bookmarks.
We will have a look into this.
Thank you for the steps to reproduce this.

**Comment by CaptainStealthy** [comment]
@XceedBoucherS No problem - please keep me in the loop on any findings.

I've attached a copy of the document I was testing with - the `dateCreated` bookmark is the form field that doesn't get replaced, and the `dateModified` bookmark is the one that got properly replaced.

Thanks!

[doc1.docx](https://github.com/xceedsoftware/DocX/files/6765775/doc1.docx)

**Comment by CaptainStealthy** [comment]
And here's the source code for my dummy console app, compiling against .NET 4.7.2

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xceed.Words.NET;

namespace DocXConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var doc = DocX.Load(@"C:\temp\doc1.docx");

            doc.Bookmarks["dateCreated"].SetText(DateTime.UtcNow.ToString());
            doc.Bookmarks["dateModified"].SetText(DateTime.UtcNow.ToString());

            doc.SaveAs(@"C:\temp\out.docx");
        }
    }
}
```

**Comment by XceedBoucherS** [comment]
Great,
Thank you for sharing this.

**Comment by XceedBoucherS** [comment]
After adding a bookmark in the "Current Date" from your doc1.docx and trying to replace it with:
`doc.Bookmarks[ "currentDate" ].SetText( DateTime.UtcNow.ToString() );`
I can see the following exception:
"System.IO.InvalidDataException: 'bookmarkStart and bookmarkEnd are not part of a paragraph. This is currently not supported.'
"
So I confirm that modifying bookmarks that are not located in Paragraphs will not work. 
Until a fix exists, try using Bookmarks inside paragraphs.

Thank you
