### ISSUE TITLE
Set absolute position for image

### ISSUE THREAD

**Issue by NeozLopez** [xceedsoftware/DocX#172]
I need to put image behind the text, are there any way to do it?

**Comment by XceedBoucherS** [comment]
Hi,
In the next release : v1.4 (scheduled for beginning of 2018), you will be able to do :
 picture.WrappingStyle = PictureWrappingStyle.WrapBehindText;

All Microsoft Word TextWrapping styles will be available :
 WrapInLineWithText,
WrapTopAndBottom,
WrapSquare,
WrapTight,
WrapThrough,
WrapBehindText,
WrapInFrontOfText

This will only be available in the "Xceed.Words for .NET", not in "DocX". You can try and buy "Xceed.Words for .NET" here : https://xceed.com/xceed-words-for-net/

Thanks.
