### ISSUE TITLE
ReplaceText  wholeword  match

### ISSUE THREAD

**Issue by mingxu2008** [xceedsoftware/DocX#180]
In a document have "12345"  and "12345678"  ,I want set "12345"  to "abcd"  but when i  ReplaceText the document be "abcd" and "abcd678" , this is not i want, how can i  get "abcd" and "12345678",thanks

**Comment by totpero** [comment]
You can use `...ReplaceText(...) `like this:
`......ReplaceText(@"\b12345\b", "abcd", escapeRegEx:false);`

Is very important to set the `@` character before the search value string.
