### ISSUE TITLE
How to use DocX/Xceed in Powershell ?

### ISSUE THREAD

**Issue by audpa33** [xceedsoftware/DocX#181]
Is it possible to use DocX/Xceed in Powershell ?

Add-Type -Path .\Docx.dll works.
After, [Novacode.DocX]::Create('somefile.docx')  or New-Object [Novacode.DocX] doesn't work.

I tried to find example without success. Is it only a .Net DLL ?

Regards

**Comment by XceedBoucherS** [comment]
Hi,
This is a dll product.
Thanks,

**Comment by audpa33** [comment]
Thanks for your reply.

Regards
