### ISSUE TITLE
 v1.5 link

### ISSUE THREAD

**Issue by satmane** [xceedsoftware/DocX#198]
Hello,
Where I can get the  v1.5 to use it? 
Thank you for your help on this.
satmane

**Comment by XceedBoucherS** [comment]
Hi,
Paying version is currently at v1.4 and is available here : https://xceed.com/xceed-words-for-net/
Free version is currently at v1.1 and is available here on GitHub.
v1.5 will be the next paying version which is still in development.
Paying versions are always some versions ahead and include special features that will never be available in the free versions.
Thank you.
