### ISSUE TITLE
read password protected docx file  With xceedsoftware.DocX?

### ISSUE THREAD

**Issue by blackholeearth** [xceedsoftware/DocX#215]
how can i open  passwordProtected.docx file  with this  exceed.docX ?

```
 // where am i gonna put the decrytion password here?????
DocX document = DocX.Load(filePath );
document.ReplaceText("name1", "George");

```

**Comment by XceedBoucherS** [comment]
Hi,
In our sample Protection/AddPasswordProtection(), the output file "Protection/Output/AdPasswordProtection.docx" will be protected from editing with a password.
To make it editable, try typing in Microsoft Word, a popup will appear. Click the "Stop protection button" and type the password "xceed". You will then be able to edit the document.

**Comment by blackholeearth** [comment]
Sorry but . Answer is invalid. İ updated my question

**Comment by XceedBoucherS** [comment]
Currently, you can open any docx file, with or without a password.
We will look into this to prevent modification when the file contains a password, and add a method to unlock the protection.
Thank you.

**Comment by blackholeearth** [comment]
> Currently, you can open any docx file, with or without a password

thats good news . so no issue/problem for me.

i  thought that i can NOT READ  docx file, if it has pasword on it.    that freaked me out. just when i thought i found a awesome docx lib

also that would be good if it's somewhere in the readme. 

2)
>  when the file contains a password, and add a method to unlock the protection. 

for me, i dont need  that kind of extra protection . any other dev would  not desperately seek that .

dont be bothered/pressured by it. 


 -------
thank you again . for this awesome project to all developers
