### ISSUE TITLE
Include pdf in word file

### ISSUE THREAD

**Issue by watoo** [xceedsoftware/DocX#222]
Hi,
I want to append pdf file in word document,
```
var pdfPath = Server.MapPath("/Content/Export/ppp.pdf");
                    var pdfDocx = DocX.Load(pdfPath); //Error: File contains corrupted data.
                    doc.InsertDocument(pdfDocx);
```

How can I include pdf in word?
Thanks

**Comment by pieteralbertstcp** [comment]
Hi Watoo,

I suspect that is not possible, you probably will have to convert from PDF to word and then import.
Good luck

**Comment by XceedBoucherS** [comment]
Hi,
It is not possible to load a pdf document. Only doc or docx document can be loaded.
