### ISSUE TITLE
Document does not load with DocX, but does load in Word (2016)

### ISSUE THREAD

**Issue by ronaldhoek** [xceedsoftware/DocX#239]
I have multiple documents with don't load with DocX but do load with Word (2016).
* Example with problem: [Test-dumping.docx](https://github.com/xceedsoftware/DocX/files/2179521/Test-dumping.docx)

StackTrace (in Dutch):

Reeks bevat geen overeenkomend element
   bij System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   bij Xceed.Words.NET.Paragraph.GetParagraphNumberProperties()
   bij Xceed.Words.NET.Paragraph.get_ParagraphNumberProperties()
   bij Xceed.Words.NET.Paragraph.get_IsListItem()
   bij Xceed.Words.NET.Container.InitParagraphs(List`1 paragraphs)
   bij Xceed.Words.NET.Container.get_Paragraphs()
   bij Xceed.Words.NET.DocX.get_Paragraphs()
   bij Xceed.Words.NET.DocX.PostLoad(Package& package)
   bij Xceed.Words.NET.DocX.Load(String filename)
   bij TestXceedDocX.frmDocXTest.btnOpenDoc_Click(Object sender, EventArgs e) in E:\Projects\.NET\_Probeersels\XceedDocX\Form1.cs:regel 34

Using VS-C# 2015 - .NET FrameWork 4.5.x

**Comment by XceedBoucherS** [comment]
Hi,
This should be fixed in v1.2

**Comment by ronaldhoek** [comment]
I thought I had installed 1.2, but it seems 1.1 was delivered thrue the NuGet package manager when selecting the ‘1.2’ package.
But I see you’ve added a 1.2.1 package to NuGet, which delivers the 1.2 assembly.

But it’s working perfectly now!

Thank you!
