### ISSUE TITLE
Website and this library / custom save location

### ISSUE THREAD

**Issue by wolfgangjt** [xceedsoftware/DocX#263]
Another effort to reach out to someone on here for some help.

I have yet to test it on the production server but is this available to be used on a website? This will be with .net 4.5 **not** core! Will my users be able to use this to create the document and save it on their local machine? If so, how can I program it to save the file to a local spot?

**Comment by ronaldhoek** [comment]
This works with the full .NET framework (as far as I can tell). I dont matter how you use the framework (winform, wpf, web, etc).

However, saving the file locally (on the clients PC) has nothing to do with the DocX library.
You’ll need to save the file on the server and then serve that file to the client using some dynamic request.

Just Google on something like: download dynamicly created files with asp.net.

**Comment by wolfgangjt** [comment]
You are a god. I spent 3 days trying to do workarounds, even trying to give ASP.NET service account permissions on my computer to write documents to. Thank you so, so, so much!
