### ISSUE TITLE
Wiki Link Doesn't Work

### ISSUE THREAD

**Issue by MattFox1388** [xceedsoftware/DocX#266]
Hello, 

I was just trying to find out more information on how to use DocX, but the documentation link gives a 404 error.

**Comment by XceedBoucherS** [comment]
Hi,

Thank you for reporting this. 
The link will be fixed.
It should point to https://xceed.com/wp-content/documentation/xceed-document-libraries-for-net/webframe.html#rootWelcome.html

**Comment by txelu** [comment]
The link is not working yet, but the issue is closed

**Comment by ronaldhoek** [comment]
Just modified the link on the Wiki page (seems I've got write access ... ?)

**Comment by txelu** [comment]
It works now. Thanks @ronaldhoek
