### ISSUE TITLE
InsertDocument error with EMF images

### ISSUE THREAD

**Issue by giarico** [xceedsoftware/DocX#272]
When you try to merge two documents with EMF images, and the images have the same name on both documents, only the images of the first document are shown.

The problem should be in the InsertDocument function. In the imageContentTypes list the content "x-emf" is missing.

Can you look at this issue?

[doc1.docx](https://github.com/xceedsoftware/DocX/files/2598940/doc1.docx)
[doc2.docx](https://github.com/xceedsoftware/DocX/files/2598941/doc2.docx)

**Comment by XceedBoucherS** [comment]
Hi,
Yes you ware right, x-emf images are not supported.
Could you please attached your 2 documents with EMF images so we can test them ?
Thank you.

**Comment by giarico** [comment]
Documents uploaded.
Sorry for the delay.

**Comment by XceedBoucherS** [comment]
Thank you.
This will be added in v1.7.

**Comment by giarico** [comment]
Tested and working
