### ISSUE TITLE
How to insert X Y (Scatter) chart?

### ISSUE THREAD

**Issue by VahedCivil** [xceedsoftware/DocX#273]
Hi
How to I can insert  X Y (Scatter) with straight line to document?
Thanks.

**Comment by XceedBoucherS** [comment]
Hi,
If you are looking for a line chart, please have a look at sample ChartSample.LineChart() from the "Examples" folder on github : https://github.com/xceedsoftware/DocX/tree/master/Examples/Samples/Chart

If not, please specify what you are missing.
Thank you.

**Comment by XceedBoucherS** [comment]
Hi,
What do you mean by " the horizontal value of Scatter Chart is double value" ?
Here's an example of a sin(x) scatter chart : 
https://plot.ly/~kmiddleton/0.embed
It contains int values on the horizontal axis, as our Line Chart.
Thank you.

**Comment by VahedCivil** [comment]
Hi Mr.  XceedBoucherS
Yes of course. We can use Int values in horizontal axis  of Scatter Chart.
Line Chart and X Y Scatter Chart are different type chart in MS Word and MS Excel.
Use a scatter chart (XY chart) to show scientific XY data. Scatter charts are often used to find out if there's a relationship between variable X and Y. 
Please see the follow links:
[https://www.microsoft.com/en-us/microsoft-365/blog/2011/08/30/line-or-scatter-chart](https://www.microsoft.com/en-us/microsoft-365/blog/2011/08/30/line-or-scatter-chart)
[https://excel-example.com/charts/difference-line-chart-scatter-chart](https://excel-example.com/charts/difference-line-chart-scatter-chart)
In scatter chart we can plot x y data same Matlab.
Please add the XY Scatter chart to your DocX package.
Thank you.

**Comment by XceedBoucherS** [comment]
Hi,
Thank you for the detailed information.
We will investigate to add this type of chart.
Thank you.
