### ISSUE TITLE
How to replace a paragraph with formatting text using xceed docx?

### ISSUE THREAD

**Issue by cristianmarian95** [xceedsoftware/DocX#276]
I want to replace some text in a `docx `file, and i'm using` XCeed Docx` lib, i want to ask if there is any way to replace the text with a new formatted text? For exemple i have the `%value%` (normal text) and i want to replace it with **bold text** to replace only the text i use the function `document.ReplaceText(%value%, "Bold text")`. Remark not all the replace text need to be bold and i do not know if the next is bold or not, i need the bold text only in some situations.

**Comment by XceedBoucherS** [comment]
Hi,
You can use the parameter "newFormatting" from the document.ReplaceText method to set the formatting of the replacing text : 
doc.ReplaceText( "de", "DE", false, System.Text.RegularExpressions.RegexOptions.None, new Xceed.Document.NET.Formatting() { Bold = true } );

You can always use this method only to replace in a specific paragraph : 
doc.Paragraphs[ 0 ].ReplaceText( "de", "DE", false, System.Text.RegularExpressions.RegexOptions.None, new Xceed.Document.NET.Formatting() { Bold = true } );

**Comment by outthin** [comment]
Hi ,
When i use the code:
doc.ReplaceText( "de", "DE", false, System.Text.RegularExpressions.RegexOptions.None, new Xceed.Words.NET.Formatting() { Bold = true } );
IT happens :System.ArgumentOutOfRangeException: Value must be one of the following: 200, 150, 100, 90, 80, 66, 50 or 33
