### ISSUE TITLE
Table AutoFit Fixed throws exception

### ISSUE THREAD

**Issue by ShevekAnarre** [xceedsoftware/DocX#301]
Although the documentation and enumeration show that you can set the AutoFit to Fixed for a table. When you try and do so it causes an "Object reference not set to an instance of an object." Exception.
Table t = document.InsertTable(1, 7);
                                t.AutoFit = AutoFit.Contents;
                                t.AutoFit = AutoFit.Window;
                                t.AutoFit = AutoFit.ColumnWidth;
                                t.AutoFit = AutoFit.Fixed;

public enum AutoFit
    {
        Contents = 0,
        Window = 1,
        ColumnWidth = 2,
        Fixed = 3
    }

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v1.5 and up.
You can try with the latest version v1.6 available here (https://xceed.com/xceed-words-for-net/) for free for 45 days.
Thank you.
