### ISSUE TITLE
Edit Data Chart

### ISSUE THREAD

**Issue by Scantraxx123** [xceedsoftware/DocX#308]
Hey!
Another Issue, for me it is not possible to edit the data in word of a chart when its created with the libary.
Is it possible?

Best regards
Felix

**Comment by XceedBoucherS** [comment]
Hi,
You can try with the commercial version available for free for 45 days here : https://xceed.com/xceed-words-for-net/
It includes a "ModifyChartData" example where "categories" and "values" are modified.
Thank you.
