### ISSUE TITLE
Using DocX.ConvertToPdf with custom styles throw an exception

### ISSUE THREAD

**Issue by cosimochellini** [xceedsoftware/DocX#323]
Using this code 

```
var pathStart = @"D:\path\to\First.docx";
var pathFinal = @"D:\path\to\final.pdf";

using (var document = DocX.Load(pathStart ))
   {
         DocX.ConvertToPdf(document, pathFinal);
   }
```
with a document with custom styles throw an exception 
![image](https://user-images.githubusercontent.com/24718181/57440773-eebbaf00-7248-11e9-9c00-0dc31091b52b.png)
(no inner exception).

you can try with this mock file
[start.docx](https://github.com/xceedsoftware/DocX/files/3161154/start.docx)

**Comment by XceedBoucherS** [comment]
Hi,

Trying with v1.3, the document "start.docx" is correctly converted to pdf without any exception.
The exception shown here usually happens when trying to convert a docx while it is opened in MS Word.
