### ISSUE TITLE
DocX.cs Bookmarks performance issue

### ISSUE THREAD

**Issue by ShevekAnarre** [xceedsoftware/DocX#325]
With the current code the larger the document the longer this will take to find all the bookmarks as it has to go through each paragraph.

public BookmarkCollection Bookmarks
    {
      get
      {
        var bookmarks = new BookmarkCollection();
        var documentBookmarks= Xml.Descendants(XName.Get("bookmarkStart", DocX.w.NamespaceName));
        foreach (var bookmark in documentBookmarks)
        {
            bookmarks.Add( new Bookmark
            {
                Name = bookmark.LastAttribute.Value,
                Paragraph = new 
Paragraph(this,bookmark.Parent,Convert.ToInt16(bookmark.FirstAttribute.Value))
            });
        }
        //for( int i = 0; i < this.Paragraphs.Count; ++i )
        //{
        //  bookmarks.AddRange( this.Paragraphs[ i ].GetBookmarks() );
        //}
        return bookmarks;
      }
    }

**Comment by XceedBoucherS** [comment]
Hi,
Thank you for pointing this out.
This optimization will be included in v1.7.
