### ISSUE TITLE
File contains corrupted data when applying to doc files

### ISSUE THREAD

**Issue by B45man** [xceedsoftware/DocX#335]
I have created a .doc file in Word. This file opens and functions correctly inside of Word.  However, when I try to load this file, the below code fails: 

```
Byte[] data = File.ReadAllBytes("myFile.doc");
using (var inputStream = new MemoryStream(data))
using (var outputStream = new MemoryStream())
using (DocX document = DocX.Load(inputStream))
{
 // code here
}
```

This code throws an exception with the message "File contains corrupted data." when calling DocX.Load(inputStream). What am I doing wrong?

**Comment by XceedBoucherS** [comment]
Hi,

When you save an MS Word document as "doc", MS Word will tell you that this is a 1997-2003 format.
this "DocX" product manages "docx" document as said on the GitHub main page : 
"DocX is a .NET library that allows developers to manipulate Word 2007/2010/2013 files,"

The format of a "docx" document is different than a "doc" document.
