### ISSUE TITLE
Paragraph Indent calculation off

### ISSUE THREAD

**Issue by ShevekAnarre** [xceedsoftware/DocX#343]
The calculation for paragraph indent levels is incorrect. It is multiplying the float value * 570. The passed in value is based on 72 points per inch and the openxml value is 1440 twips = 1 in. The correct calculation should be to multiple or divide by 20.  I am including updated Paragraph and Margin Sample code.

[MarginSample.zip](https://github.com/xceedsoftware/DocX/files/3875841/MarginSample.zip)

Also the example in the follow link is incorrect as it will never show a hanging indent of .5 inch.
https://s12316.pcdn.co/wp-content/documentation/xceed-document-libraries-for-net/webframe.html#Xceed.Document.NET~Xceed.Document.NET.Paragraph~IndentationHanging.htm

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v3.8.
This version is available for the users of "Xceed Words for .NET". You can try it for free for 45 days here : https://xceed.com/xceed-words-for-net/

v3.8 is the next scheduled release for the community.
Thank you.

**Comment by ShevekAnarre** [comment]
Thanks. I didn't see this fix listed in the notes for 1.6. Are the examples going to be updated as well? or it least the code example?

**Comment by XceedBoucherS** [comment]
Hi, yes, everything will be updated.
Here's the release note for the next community release : v1.6:
https://xceed.com/release-notes/#words-net-1.6.19076.19550
You can read : "In all classes, points are now used to set sizes, margins and spacings."
