### ISSUE TITLE
Unclear float measurements

### ISSUE THREAD

**Issue by Norrica** [xceedsoftware/DocX#344]
I am trying to change size of the list, by
`doc.PageHeight = 29.7f;`
`doc.PageWidth = 41.99f;`

Are these inches or cm? 

It doesn't matter, because resulting height is 1.05 cm, width is 1.48 cm. 

Maybe consider adding Methods/Fields `HeightInCm` or similar?

**Comment by ShevekAnarre** [comment]
From the documentation.
https://s12316.pcdn.co/wp-content/documentation/xceed-document-libraries-for-net/webframe.html#Xceed.Document.NET~Xceed.Document.NET.Document~PageHeight.html

The page height (in points) of the first Section in the Document.
Remarks
This property expects a value expressed in points (pt).

To convert to 20th of a point (dxa) : pt*20
To convert to Inches (in) : pt*72
To convert to Centimeters (cm) : in*2.54
