### ISSUE TITLE
Xceed Community License - Non commercial use

### ISSUE THREAD

**Issue by PrzemyslawKlys** [xceedsoftware/DocX#345]
Can you please explain what do you mean by non-commercial use just so it's clear for everyone? Do you mean one can't make money with it but can use it for business purposes? For example, a company generates invoices with it? Or the company generates documents for their clients about their portfolio? In other words, it uses it internally to do some automation tasks, but does not sell services based on it?

My understanding of license is that one can still use it for internal business needs but can't sell services based on DocX generation (for example selling software that generates invoices). 

Is this correct? If not, can you please clarify?

**Comment by XceedBoucherS** [comment]
Hi Klys,

For the moment, your interpretation is correct, but Xceed keep the right to modify this.

Thank you
