### ISSUE TITLE
Symbol Field

### ISSUE THREAD

**Issue by Mandivamba** [xceedsoftware/DocX#346]
Is the a way to insert symbols using the Symbol Field or is this supported in the paid version?
![2019-12-03 11_27_00-Field](https://user-images.githubusercontent.com/19623585/70018108-029d7880-15c0-11ea-8166-75dce6600166.png)

**Comment by XceedBoucherS** [comment]
Hi,
Currently no. But if you only want symbols, you can use the "symbol" font:
  doc.InsertParagraph( "test" ).Font("Symbol");
