### ISSUE TITLE
Document.NET.Image from DocX.AddImage throws ObjectDisposedException

### ISSUE THREAD

**Issue by BlueFrog76** [xceedsoftware/DocX#354]
I just updated to version 1.6.0.0 of Xceed.Document.NET and in attempting to insert an image as follows and documented elsewhere, I get an ObjectDisposedException: Package object was closed and disposed, so cannot carry out operations on this object or any stream opened on a part of this package.

Xceed.Document.NET.Image logoImg = doc.AddImage(imgFilePath); // Exception thrown here
Xceed.Document.NET.Picture logoPic = logoImg.CreatePicture();
doc.ReplaceTextWithObject("#LOGO", logoPic);

Even just calling doc.AddImage(filepath) throws an image.  I can't see how to get the Image to create the picture for inserting.  I cannot find any information on the constructor for Xceed.Document.NET.Image arguments.  In the source repository, it looks that it is not a publicly available constructor.  Is there a new way of doing this?  I get the same error if I use a FileStream instead of the image path.

**Comment by XceedBoucherS** [comment]
Hi,
Hum...strange. You can see in the samples how to add images (https://xceed.com/xceed-words-for-net/) in sample "Image/ AddPicture()".
Can you paste a complete sample with the image if you still can't find a way ?
Thank you.

**Comment by XceedBoucherS** [comment]
Hi, 
I have try your code in DocX v2.2, the latest available on GitHub/NuGet, and was able to add the picture you attached here without any exception.  

From what I understand, only calling 
Xceed.Document.NET.Image logoImg = report.AddImage(filename); // Exception thrown here
should be enough to throw the exception.
I used your image as a "SaveAs" from here, and it was saved as a jpg, so I used that jpg.

Maybe your document has something special ? Can you attached it so we can have a look. 
Do you have the same exception with other logo files (extension type, size...). If yes, there must be an issue with the document. If not, the logo must have something wrong.

Thank you

**Comment by BlueFrog76** [comment]
Yes, I have the same exception regardless of what image I try.  I have attached the document I am trying to insert the image into
[ReportTemplate.docx](https://github.com/xceedsoftware/DocX/files/8871649/ReportTemplate.docx)
.  The image is getting inserted and replacing the text on the cover page where it says #LOGO.  You can see that in the code above for the method I'm using to do that.  However, the exception occurs before I ever get to the point of placing the image on the page.  Is there a way I can troubleshoot issues with the document?  Inserting the logo image is actually the first thing I'm doing after updating the headers and footers.

public void WriteDocXReport()
        {
            string templateFile = Application.StartupPath + "\\templates\\ReportTemplate.docx";

            //Load Template file
            Xceed.Words.NET.DocX report = Xceed.Words.NET.DocX.Load(templateFile);
            report.SaveAs(this.wordFileName);

            // write footer stuff
            Version v = new Version(Application.ProductVersion);

            report.Footers.First.ReplaceText("#FOOTER", this.footer);
            report.Footers.Odd.ReplaceText("#FOOTER", this.footer);
            
            if (report.FindUniqueByPattern("VERNO", System.Text.RegularExpressions.RegexOptions.None).Count > 0)
            {
                report.ReplaceText("#VERNO", string.Format("{0}.{1}", v.Major, v.Minor));
            }

            // write cover page
            WriteReportCoverPage(report); // Insert Logo is the first thing done in the WriteCoverPage routine.
            
            // write report body
            WriteReportBody(report);

            report.Bookmarks.RemoveRange(0, report.Bookmarks.Count);
            report.SaveAs(this.wordFileName);
            report.Dispose();
        }

**Comment by XceedBoucherS** [comment]
Hi,

Ok, I can see why.
Near the beginning of your code, you call
 report.SaveAs(this.wordFileName);
just after loading the templateFile.
But it's not necessary. This will dispose the document because we usually save when we are done.
You already do a 
report.SaveAs(this.wordFileName);
near the end.

Remove the first
report.SaveAs(this.wordFileName);
and it should work.
Thank you

**Comment by BlueFrog76** [comment]
Thanks, that does appear to have fixed my issue.  Now I just have to figure out some of the other updates to code functionality since it can't find paragraphs inside tables now.
