### ISSUE TITLE
Is it possible to read data from word 97-2003 ("*.doc) files with DocX ?

### ISSUE THREAD

**Issue by vinodvinu** [xceedsoftware/DocX#358]
Hi, i just tried to read data from my word 97-2003 file but the error message says document contains corrupted data. In your docs, i can't see that this is spporting word 97-2003 files.

**Comment by XceedBoucherS** [comment]
Hi,
No there is no guarantee that DocX will read "doc" documents. Our software is mainly build for "docx" documents. You could try to convert your "doc" to "docx" before using DocX to work on it.
