### ISSUE TITLE
Images from XML

### ISSUE THREAD

**Issue by MAkcanca** [xceedsoftware/DocX#362]
I'm currently using a logic like
`foreach (var element in elmns.Xml.Elements())` where elmns is Paragraph to loop through elements and parse the document because there are some specific tags with special cases (such as math tags). There are also images in the document but I couldn't find any pattern to get images from XML. 
What is the best approach in here?

**Comment by XceedBoucherS** [comment]
Hi,

you need to look for the "drawing" tag. You will find in attachment the xml look of a picture from inside a paragraph tag.

But the easiest way is to get the paragragh's pictures with paragraph.Pictures. It will return a List<Picture>.



`<w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:pPr />
  <w:r>
    <w:rPr>
      <w:lang w:val="en-US" />
    </w:rPr>
    <w:t>- Here is a simple picture added from disk:</w:t>
  </w:r>
  <w:r>
    <w:rPr>
      <w:lang w:val="en-US" />
    </w:rPr>
    <w:br />
  </w:r>
  <w:r xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
    <drawing xmlns="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <wp:inline distT="0" distB="0" distL="0" distR="0" simplePos="0" relativeHeight="0" behindDoc="0" locked="0" layoutInCell="1" allowOverlap="1" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">
        <wp:simplePos x="0" y="0" />
        <wp:positionH relativeFrom="margin">
          <wp:align>left</wp:align>
        </wp:positionH>
        <wp:positionV relativeFrom="margin">
          <wp:align>top</wp:align>
        </wp:positionV>
        <wp:extent cx="1428750" cy="1428750" />
        <wp:effectExtent l="0" t="0" r="0" b="0" />
        <wp:wrapNone />
        <wp:docPr id="1" name="" descr="" />
        <wp:cNvGraphicFramePr>
          <a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" noChangeAspect="1" />
        </wp:cNvGraphicFramePr>
        <a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
          <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
            <pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
              <pic:nvPicPr>
                <pic:cNvPr id="0" name="" />
                <pic:cNvPicPr />
              </pic:nvPicPr>
              <pic:blipFill>
                <a:blip r:embed="Rdd596e712f734e04" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" />
                <a:stretch>
                  <a:fillRect />
                </a:stretch>
              </pic:blipFill>
              <pic:spPr>
                <a:xfrm>
                  <a:off x="0" y="0" />
                  <a:ext cx="1428750" cy="1428750" />
                </a:xfrm>
                <a:prstGeom prst="rect">
                  <a:avLst />
                </a:prstGeom>
              </pic:spPr>
            </pic:pic>
          </a:graphicData>
        </a:graphic>
      </wp:inline>
    </drawing>
  </w:r>
</w:p>`

**Comment by MAkcanca** [comment]
Thanks for the answer! Although when you use paragraph. Pictures you can't access the pure XML so I can't use the paragraph object in this situation. I tried to look for drawing tag but it doesn't appear in most of the cases. Any insights on that?

**Comment by XceedBoucherS** [comment]
Hi,

Yes you have access to the Picture's OOXML with Paragraph.Pictures. You can use something like:
`var pics = p.Pictures;
        var pic = pics[ 0 ].Xml;`
You can also try it in the Image samples.

**Comment by MAkcanca** [comment]
But If there are multiple images in a paragraph and I don't know which image comes first, or which text, I can't determine the position of a picture. What if we need to get the pictures in the same context as text? I'm trying to parse a exam template and sometimes questions have pictures, and sometimes answers. So I can't determine the exact picture location using different objects (Pictures and Xml)

**Comment by XceedBoucherS** [comment]
Hi,

Paragraph.Pictures gives you all the pictures from a paragraph while Paragraph.Text gives you a string representing the text from a paragraph. There is also Paragraph.MagicText who gives you the formatted text from a paragraph. But yes, those are not ordered when mixing text and pictures.

You will need to find a way to know the other of apparition in a paragraph. If the paragraph contains only pictures or only text, you don't have a problem. If a paragraph is mixing pictures and text you could parse the Paragraph.Xml and look for "drawing" tags(pictures) and "t" tags(text). They will be ordered, but not always easy to parse.

**Comment by MAkcanca** [comment]
Looks like it's not possible with the current implementation of the project. Needs a little hack from there and there. Closing the issue for now.
