### ISSUE TITLE
BulletedList Bullet style type

### ISSUE THREAD

**Issue by Methodicle** [xceedsoftware/DocX#387]
I've been using an app I developed that generated bulleted lists. 
Up until today the bullets were a solid black point, I've changed no code but rebuilt my app today and now the bullets are hollow.

ex from: 
   •	List Item 1
ex to:
   o	List Item 1

without changing any code at all:
`var bulletedList = document.AddList("ListItem1", 1, ListItemType.Bulleted);
            document.AddListItem(bulletedList, "ListItem1", 1);`

**Comment by XceedBoucherS** [comment]
Hi,
This is a normal behavior.
ListItems on level 0 have black dots.
ListItems on level 1 have white circles.
...
In your case, you set your listItems to be on level 1. Set them on level 0 and you will see black dots:

` var bulletedList = document.AddList( "ListItem1", 0, ListItemType.Bulleted );
      document.AddListItem( bulletedList, "ListItem1", 0 );`

**Comment by Methodicle** [comment]
@XceedBoucherS If that's the case is there a way to get a bulletlist indented with black dots?
It's odd that this was the behaviour previously and it suddenly changed after rebuilding.

**Comment by XceedBoucherS** [comment]
Hi,
I don't remember this behavior to have changed.
You can add an indentation to ListItems. Something like this could work:
`var document = DocX.Create( "doc.docx" );

      var bulletedList = document.AddList( "ListItem1", 0, ListItemType.Bulleted, null, false, false );
      bulletedList.Items[ 0 ].IndentationFirstLine = 36f;
      document.AddListItem( bulletedList, "ListItem1", 0 );

      document.InsertList( bulletedList );

      document.Save();`

**Comment by Methodicle** [comment]
@XceedBoucherS  Thanks a bunch 👍
