### ISSUE TITLE
Get Paragraph List like XPath.

### ISSUE THREAD

**Issue by minhncud** [xceedsoftware/DocX#388]
[Template_Sample.docx](https://github.com/xceedsoftware/DocX/files/5450736/Template_Sample.docx)
Sorry, I edited title and content after read more from your source code.
- I'm trying to read a document word and extract its paragraphs to get (key, value) couples . 
- I want to create a form then compare its with real files (real file can be template word or not)
I scan each Paragraph and it's ok if (a) couple(s) in the same Paragraph. 
But sometimes, key is Paragraphs[n] and value is in the Paragraphs[n+1]. Value can be text or FollowingTables. 
So, can i get a Paragraph or a list of Paragraph like XPath or something like it?
Example: 
• Get paragraphs with their ParentContainer and "**Text/ Attribute of the Parent paragraph**."
• Get Paragraphs [p+1] when know Paragraphs[p] by anything like **Paragraph.Next**
...

Thank you.
___________

May be this is not nescessary but i only want to ask about Table:
Instead of foreach row and get cells, do you support anything like table type:
• Table with "Key" in the top row(s)
• Table with "Key" in the top column(s)
• Table with "Key" in both top row(s) and column(s) .
Example: (json)

**[{"Key":"Table1", "Values": 
[{"Key": "Row1Col1", "Value":"key_1.1"}, {"Key":"Row1Col2", "Value":"key_1.2"}, {"Key":"Row1Col3", "Value":"key_1.3"},
{"Key":"Row2Col1", "Value":"data_2.1"}, {"Key":"Row2Col2", "Value":"data_2.2"}, {"Key":"Row2Col3", "Value":"data_2.3"},
{"Key":"Row3Col1", "Value":"data_3.1"}, {"Key":"Row3Col2", "Value":"data_3.2"}, {"Key":"Row3Col3", "Value":"data_3.3"}] 
}]**

**[{"Key":"Table2", "Values": 
[{"Key": "Row1Col1", "Value":"key_1.1"}, {"Key":"Row1Col2", "Value":"data_1.2"}, {"Key":"Row1Col3", "Value":"data_1.3"},
{"Key":"Row2Col1", "Value":"key_2.1"}, {"Key":"Row2Col2", "Value":"data_2.2"}, {"Key":"Row2Col3", "Value":"data_2.3"},
{"Key":"Row3Col1", "Value":"key_3.1"}, {"Key":"Row3Col2", "Value":"data_3.2"}, {"Key":"Row3Col3", "Value":"data_3.3"}] 
}]**

**[{"Key":"Table3", "Values": 
[{"Key": "Row1Col1", "Value":"key_1.1"}, {"Key":"Row1Col2", "Value":"key_1.2"}, {"Key":"Row1Col3", "Value":"key_1.3"},
{"Key":"Row2Col1", "Value":"key_2.1"}, {"Key":"Row2Col2", "Value":"data_2.2"}, {"Key":"Row2Col3", "Value":"data_2.3"},
{"Key":"Row3Col1", "Value":"key_3.1"}, {"Key":"Row3Col2", "Value":"data_3.2"}, {"Key":"Row3Col3", "Value":"data_3.3"}] 
}]**

**Comment by XceedBoucherS** [comment]
Hi,

The next version, v1.8 of DocX, will support a Paragraph.NextParagraph/PreviousParagraph properties. Until then, no it's not supported, you'll have to manage the paragraph indexes with a for loop.
No, this kind of table type is not supported.

Thank you.

**Comment by kasusa** [comment]
p.FollowingTables  is always return `null`

**Comment by XceedBoucherS** [comment]
Hi,
If a paragraph contains a table, the Paragraph.FollowingTable shouldn't be null.
If so, please send us your document docx along with the code you are using so we can investigate.
Thank you.
