### ISSUE TITLE
Bug: ReplaceText is replacing letters from a word

### ISSUE THREAD

**Issue by AbuRuqaa** [xceedsoftware/DocX#392]
I will give you an example:
if I want to replace the word care  exactly and there's another word "carefully" the program will replace the word care from carefully, I tried adding a space to the word I want to replace but this won't change the words that is followed by a dot.

`doc.ReplaceText(searchValue: replaced_word , newValue: new_word, false, RegexOptions.IgnoreCase);`

edit: pls if u answered my question provide a code sample I have been struggling with this for a while now.

**Comment by geekworm** [comment]
Try it 
`doc.ReplaceText("care", "abc", false, RegexOptions.None | RegexOptions.Multiline, null, null, MatchFormattingOptions.ExactMatch, false, false, false);`
