### ISSUE TITLE
How to remove Image or Picture?

### ISSUE THREAD

**Issue by wtujvk** [xceedsoftware/DocX#394]
It provide Method  "ModifyImage", but no method "RemoveImage".
I have a a error Relationship  like this in the file "word\_rels\document.xml.rels" (from unzip docx file)
  `<Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../NULL"/>`
The Target is error, cannot read to stream.  I want to remove the error image and error picture.
---------------------------------
<package id="DocX" version="1.7.1" targetFramework="net461" />

**Comment by XceedBoucherS** [comment]
Hi,
The project do not include a "ModifyImage" method. It only provides a "ModifyImage" sample where an image is manually modified through a Graphics object.

In the Picture class, there is a Remove method. Maybe you can try it :
`var doc = DocX.Create("test.docx");

      var image = doc.AddImage( @"balloon.jpg" );
      var picture = image.CreatePicture( 112.5f, 112.5f );
      var p = doc.InsertParagraph( "- Here is a simple picture added from disk:\n" );
      p.AppendPicture( picture );

      doc.Pictures[0].Remove();

      doc.Save();`

It should work, but it will only removes the xml part. Relationships will remains in the document, but unused.
