### ISSUE TITLE
Close or Dispose should not save the document to disk

### ISSUE THREAD

**Issue by RupertAvery** [xceedsoftware/DocX#400]
The saving API is really confusing.

I want to open a document, then save it to another file, without overwriting the original one with the changes. The API makes it very difficult to do that "normally", what I probably mean is that _intent is unspecified_, yet it overwrites the original file without me expressly asking it to, and I can't tell it not to.

I found that if I need to make edits to a document that will persist when I save it to another file, it needs to be loaded in **isEditable** mode, I cannot load in ReadOnly mode as changes will not be persisted _even when saving to another file_. I don't know if this is clearly documented.

As a developer, I may not want to save the changes I made to the current file, and instead write it to another file.

It would also be nice if **SaveAs** didn't open the file it had just saved, needing to close it (and thus save it all over again), when I just want to write the changes to a new document.

Tracing the code I find that the document will be saved on Dispose or Close, which I think is very counterintuitive. 

Unfortunately, I understand that a lot of existing code out there probably relies on this behavior, but I think a breaking change of explicitly Saving before Disposing would not be so bad.

```
         // Load document
	using (var doc = WordprocessingDocument.Open(input, true))
	{
                // ... make changes ...
               // Save changes to another document to preserve the original (supposedly)
		using (var newdoc = doc.SaveAs(output))
		{ 
                        // yeah, no... I just want to save as... why does it create a new instance
		}
               // unfortunately disposing updates the original document... :(
	}
        // literally profit
```

My workaround is to copy the input file to a temporary file, then perform the changes on that file.

I may be completely missing some proper usage of the library that can allow me to do this, so please feel free to wreak havoc on me, but having a simple, intuitive, understandable API should also be the goal of any library.

This is an excellent library and I'm glad to be able to use it, just this minor and confusing, somewhat undocumented behavior.

**Comment by XceedBoucherS** [comment]
Hi,
Not sure exactly what you means, but the following code can edit a "ReadOnly" document and save it to a new document. You don't need to use "WordprocessingDocument".

` using( var doc = DocX.Load( "test.docx" ) )
      {
        doc.InsertParagraph("New Paragraph");
        doc.SaveAs("output.docx");
      }`

**Comment by RupertAvery** [comment]
Now I realize I am a complete idiot and posted an issue on the wrong project.
