### ISSUE TITLE
Inserting Document Starts New Page.

### ISSUE THREAD

**Issue by R-Ziegler** [xceedsoftware/DocX#410]
As comment says, inserting a document to an existing one adds a page break before inserting. If there is an option not to do this I am not seeing it.

**Comment by XceedBoucherS** [comment]
Hi,
You can try to set the Document.InsertDocument's 3rd parameter to false (useSectionBreak). Output will show each document on the same page:
` var doc1 = DocX.Load("doc1.docx");
      var doc2 = DocX.Load( "doc2.docx" );

      doc1.InsertDocument( doc2, true, false );

      doc1.SaveAs( "output.docx" );`
