### ISSUE TITLE
Insert document in a specific position

### ISSUE THREAD

**Issue by mtugnoli** [xceedsoftware/DocX#419]
Is it possible insert a document after a specific paragraph ?

**Comment by XceedBoucherS** [comment]
Hi,
Starting at v2.1(commercial version), this is possible. 
A new method Document.InsertDocument() takes a parameter specifying a documentElement (like a paragraph) from where the insertion must be done.
You can try v2.1 for free here: https://xceed.com/en/our-products/product/words-for-net or on NuGet.

Thank you.
