### ISSUE TITLE
Question about v2.0

### ISSUE THREAD

**Issue by wolfgangjt** [xceedsoftware/DocX#420]
Just a quick question to verify, the version out now on github (free) [2.0] does have the capability to convert to PDF and to generate digital signature blocks?

I am trying to test it out in my web app but have to get it approved by security, just making sure it has these capabilities that we need.

**Comment by XceedBoucherS** [comment]
Hello,
No, the free version of _DocX_ do not include conversion to PDF and Digital signatures. These features are only part of the commercial version, available to test for free for 15 days here: https://xceed.com/en/our-products/product/words-for-net

Thank you
