### ISSUE TITLE
Cant change text in the header after inserting a document

### ISSUE THREAD

**Issue by jmk1993** [xceedsoftware/DocX#427]
Hello, im not able to do something like this after inserting a document: Headers.First.Tables[1].Rows[0].Paragraphs[1].InsertText("test");

When saving the wordfile this specific cell of the table will still be empty. Any work arround ideas?

**Comment by XceedBoucherS** [comment]
Hello,
You can have a look at the paragraphs and headers samples. Try it from here: https://xceed.com/en/our-products/product/words-for-net

Here's a few suggestion:
-Make sure you have headers. Don't forget to add a header : document.AddHeaders();
-By default, the Odd header is used : document.Headers.Odd.InsertParagraph( "test " )
-The  document.Headers.First will be used when document.DifferentFirstPage = true;
-Add text in table's cell: tabe.Rows[ 0 ].Cells[ 0 ].Paragraphs[ 0 ].Append( "Mike" );

Thank you

**Comment by jmk1993** [comment]
Hello, 
Thank u for the quick respone. In my case i load one document and insert an other doucment several times to the end of that one.
In the document i open first (contains 2 pages) is already an existing first and oddheader. If i dont insert the other document i can change the values of the table in the header. Once i inserted the other document the Output wont have those changed value.
When im debugging the string value will be set to the cell until i insert the new document. from that point on the value of text is empty again.

**Comment by XceedBoucherS** [comment]
Hi,
This may be already fixed in v2.2 (soon to be released).

I haven't tested, but try going in file Xceed.Document.NET/Src/Document.cs
in method UpdateCacheSections()
and add the following at the start of the method:
this.SaveHeadersFooters();

it should save you changes in headers and footers before inserting the new document.
Thank you

**Comment by jmk1993** [comment]
Hi, 

i have seen this method when i was going to the exaples for finding a solution. But since this method is protected internal override void SaveHeadersFooters(); i cant call it by my own right?

**Comment by jmk1993** [comment]
You mean i should change the dll? How can i do that?
