### ISSUE TITLE
[question] Loop through document items

### ISSUE THREAD

**Issue by johnnyontheweb** [xceedsoftware/DocX#465]
Hello,
I searched a lot for this, but without luck.
How to access all the items in a document? This will allow to iterate through all items such as Paragraph, Pictures, Table, List, etc. maintaining their **order**.
I assume there's a public type that can be casted into a smaller type (e.g. object -> Paragraph or Table or...
Maybe an Xelement, but it this available outside the lib?

thanks in advance,

**Comment by XceedBoucherS** [comment]
Hi,

There is no properties for getting the _Paragraphs, Pictures, Tables_ and _List_ while maintaining their order in a document.

The properties _Pictures_, _Tables_ and _Lists_ from _Document_ will return the these elements in 3 distincts lists.

Your closest way of getting those element in order of appearance would be to parse the _Document.Paragraphs_ and look for Pictures/Tables...in each Paragraphs.

Thank you

**Comment by johnnyontheweb** [comment]
Hello,
thanks for the snippet, but it is not working. 
For instance: I have a docx with a table, an empty line and finally another table. I used your code (slightly modified to list tables instead of pictures), but I cannot get in any way the empty line and its order with respect to the tables.

I think a future improvement would be of great importance for a large variety of cases, e.g. copy the content of a document in another by appending it and neglecting the first document formats/headers/footers/etc.
Actually, a document containing table + empty line + table can be appended or inserted in another document only iterating on the same type (pragraph or table or picture).

**Comment by XceedBoucherS** [comment]
Hi @johnnyontheweb,

I haven't test this with Tables, but I would expect the document to look like:
-a paragraph containing a table
-a paragraph containing an empty line
-a paragraph containing a table
Therefor, parsing the paragraphs would result in the knowing which table appears before the other one. 
Or you have another kind of document composition. Could you share your docx so I could test it ?

Currently, DocX offer the possibility to append a document to another document by selecting which header/footer you want in the resulting document (the ones from the source, the ones from the target or keep both of them). Please have a look at Document.InsertDocument() method, it will append or insert a document to another one.

The commercial Xceed Words for .NET will also let you insert a document at a specific position in another document. You can try it for free for 15 days here : https://xceed.com/en/our-products/product/words-for-net

Just tell me if you need something not supported, we could add it to our todo list.
Thank you

**Comment by johnnyontheweb** [comment]
Thanks, I've already seen Document.InsertDocument() before posting here, but I'm not interested in it, because it does not fit exactly my purposes (in my case, all the layouts that have to be used are the ones from the target document, there's not a choice about headers only).

In any case, I did a complete test of your revised code, and before I was calling Document.Tables. Instead, there's not paragraph.Tables like paragraph.Pictures!
In addition, by copying paragraphs, also the text content of the tables are copied as simple text, outside cells!

I can confirm there's not possible to do what I want

**Comment by XceedBoucherS** [comment]
Hi,
In Paragraph, there is a property called _FollowingTables_, which lists the tables following this paragraph, in order they appears.
