### ISSUE TITLE
InsertContent as append from Paragraph

### ISSUE THREAD

**Issue by mirkovicmiroslav** [xceedsoftware/DocX#467]
Hello, 

`InsertContent` is adding `altChunk` on document xml with `AddAfterSelf` method at the end. 
I have observed that the current implementation consistently adds content as a new paragraph below the last one. My inquiry pertains to the possibility of utilizing the InsertContent method in a manner that allows for appending content directly from a paragraph, thus seamlessly continuing the existing paragraph without creating a new one. Or maybe merging two paragraphs funcionality or any workaround...

Ideally, the functionality I am seeking would be expressed as follows:

```
paragraph.appendContent(html)
         .appendNote(footnote);
```

Currently, if I try with `insertContent` text will be broken and footnote will not be added on right position.

I would greatly appreciate any insights or guidance you can provide on achieving this objective.
@XceedBoucherS 

Thank you for your time and assistance.

**Comment by evancekafando** [comment]
Hi,

Our latest commercial version does not add altChunk when inserting HTML content. As of inserting or appending HTML content content inside or after a paragraph, this feature will be available in the upcoming commercial version.

Thank you
-The Xceed Team

**Comment by mirkovicmiroslav** [comment]
@evancekafando 

I'm using commercial v2.5.0 and `insertContent` is always adding content in new paragraph at the end..
Is there any workaround for that?

**Comment by evancekafando** [comment]
Hi

Unfortunately, older versions are not actively updated or maintained. Regarding your specific request, we are considering including it in the upcoming commercial version that is currently in development. In the meantime, you could try playing on your own by loading and parsing your HTML string, then extract append to your paragraphs the contents and its formatting.

For example : 

// Append some extracted HTML text and formatting.
        p.Append( "Extracted HTML contents" )
        .Font( new Xceed.Document.NET.Font( "Arial" ) )
        .FontSize( 25 )
        .Color( Color.Red )
        .Bold()
        .Append( " Additianal content extracted from HTML" ).Font( new Xceed.Document.NET.Font( "Times New Roman" ) ).Color( Color.Blue ).Italic()
        .SpacingAfter( 40 );
