### ISSUE TITLE
How can I change a textbox content?

### ISSUE THREAD

**Issue by AloysiusChua0822** [xceedsoftware/DocX#479]

**Comment by XceedBoucherS** [comment]
Hello,

TextBoxes are only part of the Xceed Words for .NET, the commercial version of DocX. 
In that version, you have a property in Paragraph : TextBoxes, which returns the list of TextBox for a paragraph.
You also have a method in Document: AddTextBox(), which create a new TextBox that you can insert in a paragraph with Paragraph.InsertShape().
At this moment, you can't modify a TextBox content, but as a workaround, you can remove the original TextBox and add the new one. We will work on modifying the TextBox content
You can try it Xceed Words for .NET here: https://xceed.com/en/our-products/product/words-for-net

Thank you

**Comment by AloysiusChua0822** [comment]
Thanks a lot!
